In [24]:
import pandas as pd
import numpy as np

# https://www.kaggle.com/datasets/selfishgene/historical-hourly-weather-data
# This datasets is in the local directory

In [25]:
humidity = pd.read_csv("humidity.csv")
temp = pd.read_csv("temperature.csv")
pressure = pd.read_csv("pressure.csv")
weather = pd.read_csv("weather_description.csv")

In [26]:
humidity_Dallas = humidity[['datetime','Dallas']]
temp_Dallas = temp[['datetime','Dallas']]
pressure_Dallas = pressure[['datetime','Dallas']]
weather_Dallas = weather[['datetime','Dallas']]

In [27]:
weather_Dallas.head()

datetime        Dallas
0  2012-10-01 12:00:00           NaN
1  2012-10-01 13:00:00          mist
2  2012-10-01 14:00:00  sky is clear
3  2012-10-01 15:00:00  sky is clear
4  2012-10-01 16:00:00  sky is clear

In [29]:
print("How many NaN are there in the humidity dataset?",humidity_Dallas.isna().sum()['Dallas'])
print("How many NaN are there in the temperature dataset?",temp_Dallas.isna().sum()['Dallas'])
print("How many NaN are there in the pressure dataset?",pressure_Dallas.isna().sum()['Dallas'])

How many NaN are there in the humidity dataset? 319
How many NaN are there in the temperature dataset? 4
How many NaN are there in the pressure dataset? 60


In [30]:
humidity_Dallas.interpolate(inplace=True)
humidity_Dallas.dropna(inplace=True)

temp_Dallas.interpolate(inplace=True)
temp_Dallas.dropna(inplace=True)

pressure_Dallas.interpolate(inplace=True)
pressure_Dallas.dropna(inplace=True)

<ipython-input-30-da3625036609>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  humidity_Dallas.interpolate(inplace=True)
<ipython-input-30-da3625036609>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  humidity_Dallas.dropna(inplace=True)
<ipython-input-30-da3625036609>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_Dallas.interpolate(inplace=True)
<ipython-input-30-da3625036609>:5: SettingWithCopyWarning: 
A value is trying t

In [31]:
print("How many NaN are there in the humidity dataset?",humidity_Dallas.isna().sum()['Dallas'])
print("How many NaN are there in the temperature dataset?",temp_Dallas.isna().sum()['Dallas'])
print("How many NaN are there in the pressure dataset?",pressure_Dallas.isna().sum()['Dallas'])

How many NaN are there in the humidity dataset? 0
How many NaN are there in the temperature dataset? 0
How many NaN are there in the pressure dataset? 0


In [32]:
humidity_Dallas.head()

datetime  Dallas
1  2012-10-01 13:00:00    87.0
2  2012-10-01 14:00:00    86.0
3  2012-10-01 15:00:00    86.0
4  2012-10-01 16:00:00    86.0
5  2012-10-01 17:00:00    86.0

In [35]:
# Renaming the "Dallas" column for clarity
humidity_Dallas = humidity_Dallas.rename(columns={'Dallas': 'humidity'})
temp_Dallas = temp_Dallas.rename(columns={'Dallas': 'temperature'})
pressure_Dallas = pressure_Dallas.rename(columns={'Dallas': 'pressure'})
weather_Dallas = weather_Dallas.rename(columns={'Dallas': 'weather_description'})

In [36]:
humidity_Dallas.head()

datetime  humidity
1  2012-10-01 13:00:00      87.0
2  2012-10-01 14:00:00      86.0
3  2012-10-01 15:00:00      86.0
4  2012-10-01 16:00:00      86.0
5  2012-10-01 17:00:00      86.0

In [37]:
# Join the dataframes
df_combined = pd.merge(humidity_Dallas, temp_Dallas, on='datetime')
df_combined = pd.merge(df_combined, pressure_Dallas, on='datetime')
df_combined = pd.merge(df_combined, weather_Dallas, on='datetime')

In [38]:
df_combined.head()

datetime  humidity  temperature  pressure weather_description
0  2012-10-01 13:00:00      87.0   289.740000    1011.0                mist
1  2012-10-01 14:00:00      86.0   289.762974    1011.0        sky is clear
2  2012-10-01 15:00:00      86.0   289.830767    1011.0        sky is clear
3  2012-10-01 16:00:00      86.0   289.898560    1011.0        sky is clear
4  2012-10-01 17:00:00      86.0   289.966352    1011.0        sky is clear

In [39]:
print("How many NaN are there in the weather_description column?",df_combined.isna().sum()['weather_description'])

How many NaN are there in the weather_description column? 0


In [45]:
unique_weather = df_combined['weather_description'].unique()
print(unique_weather)

# Seperate the weather between 0 and 1
# Where 0 is no precipitation
# 1 is some precipitation/heavy weather

replacement_dict = {'mist': 0, 'sky is clear': 0, 'few clouds': 0, 'overcast clouds': 0,
                    'scattered clouds': 0, 'broken clouds': 0, 'light intensity drizzle': 1,
                    'light rain': 1, 'fog': 0, 'haze': 0, 'heavy snow': 1, 'dust': 0,
                    'proximity thunderstorm': 1, 'thunderstorm with rain': 1, 'thunderstorm': 1,
                    'thunderstorm with heavy rain': 1, 'heavy intensity rain': 1, 'moderate rain': 1,
                    'drizzle': 1, 'heavy intensity drizzle': 1, 'thunderstorm with light rain': 1,
                    'proximity thunderstorm with rain': 1, 'thunderstorm with heavy drizzle': 1,
                    'very heavy rain': 1, 'smoke': 0, 'light snow': 1, 'snow': 1, 'squalls': 1,
                    'thunderstorm with light drizzle': 1, 'tornado': 1, 'thunderstorm with drizzle': 1,
                    'proximity shower rain': 1}


df_combined['weather_description'].replace(replacement_dict, inplace=True)

df_combined.head()

['mist' 'sky is clear' 'few clouds' 'overcast clouds' 'scattered clouds'
 'broken clouds' 'light intensity drizzle' 'light rain' 'fog' 'haze'
 'heavy snow' 'dust' 'proximity thunderstorm' 'thunderstorm with rain'
 'thunderstorm' 'thunderstorm with heavy rain' 'heavy intensity rain'
 'moderate rain' 'drizzle' 'heavy intensity drizzle'
 'thunderstorm with light rain' 'proximity thunderstorm with rain'
 'thunderstorm with heavy drizzle' 'very heavy rain' 'smoke' 'light snow'
 'snow' 'squalls' 'thunderstorm with light drizzle' 'tornado'
 'thunderstorm with drizzle' 'proximity shower rain']


datetime  humidity  temperature  pressure  weather_description
0  2012-10-01 13:00:00      87.0   289.740000    1011.0                    0
1  2012-10-01 14:00:00      86.0   289.762974    1011.0                    0
2  2012-10-01 15:00:00      86.0   289.830767    1011.0                    0
3  2012-10-01 16:00:00      86.0   289.898560    1011.0                    0
4  2012-10-01 17:00:00      86.0   289.966352    1011.0                    0

In [52]:
# Trying RNN from Keras/tensorflow

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN, Embedding
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.model_selection import train_test_split

# Assuming df_combined is your final DataFrame after merging and preprocessing
X = df_combined[['humidity', 'temperature', 'pressure']].values
Y = df_combined['weather_description']

# One-hot encode the target variable
Y_onehot = to_categorical(Y)

# Normalize input features
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Reshape X to match RNN input shape
X_rnn = X_scaled.reshape((X_scaled.shape[0], 1, X_scaled.shape[1]))

# Split the data into training and testing sets
split_index = int(0.8 * len(X_rnn))
X_train, X_test = X_rnn[:split_index], X_rnn[split_index:]
Y_train, Y_test = Y_onehot[:split_index], Y_onehot[split_index:]

In [53]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense

# Define the RNN model
model = Sequential([
    SimpleRNN(50, input_shape=(X_train.shape[1], X_train.shape[2]), activation='relu'),
    Dense(32, activation='relu'),
    Dense(len(label_encoder.classes_), activation='softmax')
])

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, Y_train, epochs=20, batch_size=32, validation_data=(X_test, Y_test), verbose=2)

Epoch 1/20
1132/1132 - 5s - loss: 0.3906 - accuracy: 0.8427 - val_loss: 0.3277 - val_accuracy: 0.8876 - 5s/epoch - 5ms/step
Epoch 2/20
1132/1132 - 3s - loss: 0.3574 - accuracy: 0.8603 - val_loss: 0.3318 - val_accuracy: 0.8875 - 3s/epoch - 3ms/step
Epoch 3/20
1132/1132 - 3s - loss: 0.3549 - accuracy: 0.8635 - val_loss: 0.3351 - val_accuracy: 0.8816 - 3s/epoch - 3ms/step
Epoch 4/20
1132/1132 - 5s - loss: 0.3527 - accuracy: 0.8649 - val_loss: 0.3331 - val_accuracy: 0.8822 - 5s/epoch - 5ms/step
Epoch 5/20
1132/1132 - 4s - loss: 0.3530 - accuracy: 0.8648 - val_loss: 0.3343 - val_accuracy: 0.8806 - 4s/epoch - 3ms/step
Epoch 6/20
1132/1132 - 3s - loss: 0.3509 - accuracy: 0.8660 - val_loss: 0.3322 - val_accuracy: 0.8831 - 3s/epoch - 3ms/step
Epoch 7/20
1132/1132 - 4s - loss: 0.3507 - accuracy: 0.8667 - val_loss: 0.3341 - val_accuracy: 0.8806 - 4s/epoch - 4ms/step
Epoch 8/20
1132/1132 - 3s - loss: 0.3499 - accuracy: 0.8672 - val_loss: 0.3365 - val_accuracy: 0.8788 - 3s/epoch - 3ms/step
Epoch 9/

In [49]:
print(len(label_encoder.classes_))

2


In [50]:
print(X_train)

[[[0.85714286 0.53286312 0.34782609]]

 [[0.84615385 0.53329833 0.34782609]]

 [[0.84615385 0.53458253 0.34782609]]

 ...

 [[0.52747253 0.66319166 0.35869565]]

 [[0.41758242 0.68497623 0.34782609]]

 [[0.36263736 0.71092828 0.31521739]]]


In [51]:
print(Y_train)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [0. 1.]]
